const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const hexToRgb=h=>{h=h.replace('#','');if(h.length===3)h=[...h].map(x=>x+x).join('');let n=parseInt(h,16);return{r:n>>16&255,g:n>>8&255,b:n&255}};
const rgbToHex=({r,g,b})=>'#'+[r,g,b].map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('');
const rgbToHsl=({r,g,b})=>{r/=255;g/=255;b/=255;let max=Math.max(r,g,b),min=Math.min(r,g,b),h=0,s,l=(max+min)/2,d=max-min;if(d){s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;case b:h=(r-g)/d+4}h*=60}return{h:Math.round(h),s:Math.round(s*100),l:Math.round(l*100)}};
const hslToRgb=({h,s,l})=>{s/=100;l/=100;let c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2,r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return{r:(r+m)*255,g:(g+m)*255,b:(b+m)*255}};
const setCode=css=>{$('#code').textContent=css}; const copy=()=>navigator.clipboard?.writeText($('#code').textContent);
function init(){let page=document.body.dataset.tool;if(!page)return; $$('.copy').forEach(b=>b.onclick=copy); $$('input,select,textarea').forEach(i=>i.addEventListener('input',render)); render()}
function render(){let p=document.body.dataset.tool, t=$('#target'); if(!t)return;
 if(p==='border-image'){let src=$('#biSource').value==='gradient'?`linear-gradient(${$('#angle').value}deg, ${$('#c1').value}, ${$('#c2').value}, ${$('#c3').value})`:`url(${$('#imageUrl').value})`;let css=`border: ${$('#borderWidth').value}px solid transparent;\nborder-image-source: ${src};\nborder-image-slice: ${$('#slice').value};\nborder-image-width: ${$('#biWidth').value};\nborder-image-outset: ${$('#outset').value};\nborder-image-repeat: ${$('#repeat').value};`;t.style.cssText=`${css} background:#f5d77b;`;setCode(`.royal-border {\n  ${css.replaceAll('\n','\n  ')}\n}`)}
 if(p==='radius'){let vals=$$('.radius').map(i=>i.value+'px'), oval=$$('.oval').map(i=>i.value+'px');let br=`${vals.join(' ')} / ${oval.join(' ')}`;t.style.borderRadius=br;t.style.background=$('#fill').value;setCode(`.royal-radius {\n  border-radius: ${br};\n  background: ${$('#fill').value};\n}`)}
 if(p==='shadow'){let shadows=[];for(let i=1;i<=3;i++){if($('#on'+i).checked)shadows.push(`${$('#inset'+i).checked?'inset ':''}${$('#x'+i).value}px ${$('#y'+i).value}px ${$('#blur'+i).value}px ${$('#spread'+i).value}px ${$('#sc'+i).value}${Math.round($('#alpha'+i).value*255).toString(16).padStart(2,'0')}`)}let css=shadows.join(', ');t.style.boxShadow=css;setCode(`.royal-shadow {\n  box-shadow: ${css};\n}`)}
 if(p==='converter'){let rgb=hexToRgb($('#color').value),hsl=rgbToHsl(rgb),ok=`oklch(${(hsl.l/100*.9).toFixed(2)} ${(hsl.s/100*.25).toFixed(2)} ${hsl.h})`;t.style.background=$('#color').value;setCode(`HEX: ${$('#color').value}\nRGB: rgb(${rgb.r}, ${rgb.g}, ${rgb.b})\nHSL: hsl(${hsl.h} ${hsl.s}% ${hsl.l}%)\nOKLCH: ${ok}\nContrast text: ${hsl.l>55?'#12071f':'#f8f0d7'}`)}
 if(p==='mixer'){let a=hexToRgb($('#a').value),b=hexToRgb($('#b').value),m=$('#mix').value/100,mode=$('#mode').value;let out;if(mode==='hsl'){let ah=rgbToHsl(a),bh=rgbToHsl(b);out=hslToRgb({h:ah.h+(bh.h-ah.h)*m,s:ah.s+(bh.s-ah.s)*m,l:ah.l+(bh.l-ah.l)*m})}else out={r:a.r+(b.r-a.r)*m,g:a.g+(b.g-a.g)*m,b:a.b+(b.b-a.b)*m};let hex=rgbToHex(out);t.style.background=hex;$$('.swatch').forEach((s,i)=>{let mm=i/4;s.style.background=rgbToHex({r:a.r+(b.r-a.r)*mm,g:a.g+(b.g-a.g)*mm,b:a.b+(b.b-a.b)*mm})});setCode(`Mixed color: ${hex}\nbackground: ${hex};`)}
 if(p==='shape'){let shape=$('#shape').value,css=''; if(shape==='blob')css='polygon(50% 0%, 86% 12%, 100% 54%, 76% 100%, 25% 91%, 0% 48%, 14% 10%)'; if(shape==='diamond')css='polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)'; if(shape==='triangle')css='polygon(50% 0%, 0% 100%, 100% 100%)'; if(shape==='badge')css='polygon(25% 0%, 75% 0%, 100% 25%, 100% 75%, 75% 100%, 25% 100%, 0% 75%, 0% 25%)'; if(shape==='circle')css=`circle(${$('#size').value}% at ${$('#posx').value}% ${$('#posy').value}%)`;t.style.clipPath=css;t.style.background=$('#shapeColor').value;setCode(`.royal-shape {\n  clip-path: ${css};\n  background: ${$('#shapeColor').value};\n}`)} }
document.addEventListener('DOMContentLoaded',init);
